routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\Articles\ArticleController;
use App\Http\Controllers\Web\Users\UserController;
use App\Http\Controllers\Web\Socials\SocialController;
use App\Http\Controllers\Web\Auth\LoginController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

# Websocket
Route::group([], function () {
    if (config('app.env') == 'local') {
        #測資
        Route::group(['middleware' => ['SocketOnline', 'web']], function () {
            Route::get('/user', [UserController::class, 'index']);
        });
        Route::get('/trigger/{data}', function ($data) {
            echo "<p>You have sent $data</p>";
            event(new App\Events\GetRequestEvent($data));
        });
    }
    # PWA
    Route::get('/offline', function () {
        return response('', 200);
    });
});
# Blog
Route::group([], function () {
    Route::name("website.index")->get('/', [ArticleController::class, 'index']);
    Route::resource('article', ArticleController::class)->only(['index', 'create', 'show', 'edit']);
    Route::get('/upload', function () {
        return view('upload');
    });
# 登入
    Route::post('/login', [LoginController::class, 'login'])->name('login.api');
# 第三方登入
    Route::group(['as' => 'social.', 'prefix' => 'social'], function () {
        Route::group(['as' => 'line.', 'prefix' => 'line'], function () {
            Route::name("login")->get("/login", [SocialController::class, 'lineLogin']);
            Route::name("return")->get("/return", [SocialController::class, 'lineReturn']);
            #用戶資料刪除
            Route::name("delete")->get("/delete", [SocialController::class, 'lineDelete']);
        });
        Route::group(['as' => 'facebook.', 'prefix' => 'facebook'], function () {
            Route::name("login")->get("/login", [SocialController::class, 'facebookLogin']);
            Route::name("return")->get("/return", [SocialController::class, 'facebookReturn']);
            #用戶資料刪除
            Route::name("delete")->get("/delete", [SocialController::class, 'facebookDelete']);
        });
    });
});

resources/views/layouts/footer.blade.php
<footer class="border-top">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://www.instagram.com/comman24/" alt="instagram" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://www.facebook.com/roy22887" alt="facebook" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/cc711612" alt="github" target="_blank">
                            <span class="fa-stack fa-lg">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Copyright &copy; 2021 Roy<p
                        id="busuanzi_value_site_pv"></p></div>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'blog') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

        <!-- Scripts -->
{{--        <script src="{{ mix('js/app.js') }}" defer></script>--}}
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{{route('website.index')}}">{{ config('app.name', 'Laravel') }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{route('website.index')}}">Home</a>
                </li>
                @if(is_null(\Illuminate\Support\Facades\Auth::user()))
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{route('login')}}">LOGIN</a>
                    </li>
                @else
                    @if(in_array(\Illuminate\Support\Facades\Auth::id(),config('admin.user_ids')))
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{route('admin.home')}}">Admin</a>
                        </li>
                    @endif
                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{{route('article.create')}}">POST</a>
                    </li>

                    <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" id="logout" href="/logout">LOGOUT</a>
                    </li>
                @endif
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/tracking_header.blade.php
@if(is_null(config('services.google.tag')) === false)
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','{{config('services.google.tag')}}');
</script>
<!-- End Google Tag Manager -->
@endif

resources/views/layouts/tracking_noscript.blade.php
@if(is_null(config('services.google.tag')) === false)
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id={{config('services.google.tag')}}"
                  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
@endif